<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper
PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
"http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="com.jndi.jti.board.mapper.mysql.TxMysqlMapper">
	<select id="mysqlRead" resultType="TxMysqlParam" parameterType="Integer">
	    select * from board where bid = 1
	</select>

	<update id="mysqlUpdate" parameterType="TxMysqlParam">
        update board set content = #{content} where bid = 1
    </update>
</mapper>