# jndi 사용 여부 true, false
# true일 경우 config-location, mapper-locations에 대한 정보만 있으면 된다.
spring:
  mysql:
    datasource:
     jndi: true
#       jndi: false
  oracle:
    datasource:
     jndi: true
#       jndi: false
  # REDIS
  redis:
    object:
      host: your_server_ip
      port: 6379
      database: 0
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    session:
      host: your_server_ip
      port: 6379

# MYSQL, ORACLE
ttaeinee:
  datasource:
    mysql:
      config-location: classpath:mybatis/mybatis-config-mysql.xml
      mapper-locations: classpath:mybatis/**/mapper/mysql/*Mapper.sqlx
#       driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#       url: jdbc:log4jdbc:mysql://192.168.137.93:3306/javatest
#       username: wasdb
#       password: root
    oracle:
      config-location: classpath:mybatis/mybatis-config-oracle.xml
      mapper-locations: classpath:mybatis/**/mapper/oracle/*Mapper.sqlx
#       driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#       url: jdbc:log4jdbc:oracle:thin:@192.168.137.93:1521:XE
#       username: system
#       password: oracle




